### ISSUE TITLE
Implement searching and querying pattern data

### ISSUE THREAD

**Issue by Maddoxx88** [Maddoxx88/microregex#26]
#### TODO

- [ ] Create new query for searching patterns
- [ ] Display filtered results 
- [ ] Filter according to tags
