### ISSUE TITLE
Changes in shading and colors

### ISSUE THREAD

**Issue by Maddoxx88** [Maddoxx88/microregex#29]
#### TODO

- [ ] lighter tag bg
- [ ] lighter name
- [ ] darker preview text
- [ ] input colors and shading

**Comment by Maddoxx88** [comment]
Take it up @localhoax
