### ISSUE TITLE
Display preview text on the card highlight

### ISSUE THREAD

**Issue by Maddoxx88** [Maddoxx88/microregex#32]
#### TODO

- [ ] Replace content with preview text in card
- [ ] Copied text must be content specific to the language
- [ ] Preview text is the required regex
